#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.DB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TestDB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void InsertBaseTMT(BaseTMT instance);
    partial void UpdateBaseTMT(BaseTMT instance);
    partial void DeleteBaseTMT(BaseTMT instance);
    partial void Inserttbl_Fiches(tbl_Fiches instance);
    partial void Updatetbl_Fiches(tbl_Fiches instance);
    partial void Deletetbl_Fiches(tbl_Fiches instance);
    partial void Inserttbl_Immeuble(tbl_Immeuble instance);
    partial void Updatetbl_Immeuble(tbl_Immeuble instance);
    partial void Deletetbl_Immeuble(tbl_Immeuble instance);
    partial void Inserttbl_Proprio(tbl_Proprio instance);
    partial void Updatetbl_Proprio(tbl_Proprio instance);
    partial void Deletetbl_Proprio(tbl_Proprio instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::TestApp.Properties.Settings.Default.TestDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BaseTMT> BaseTMT
		{
			get
			{
				return this.GetTable<BaseTMT>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Fiches> tbl_Fiches
		{
			get
			{
				return this.GetTable<tbl_Fiches>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Immeuble> tbl_Immeuble
		{
			get
			{
				return this.GetTable<tbl_Immeuble>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Proprio> tbl_Proprio
		{
			get
			{
				return this.GetTable<tbl_Proprio>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BaseTMT")]
	public partial class BaseTMT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Numero;
		
		private string _Titre;
		
		private string _Prénom;
		
		private string _Nom_Propriétaire;
		
		private string _Numéro_rue_Propriétaire;
		
		private string _TypeRuePropriétaire;
		
		private string _Rue_Propriétaire;
		
		private string _Code_Postal_Propriétaire;
		
		private string _Ville_Propriétaire;
		
		private string _TypeRueImmeuble;
		
		private string _Commentaire_2;
		
		private string _Rue_Immeuble;
		
		private string _Ville_Immeuble;
		
		private string _Asterix;
		
		private string _Commentaire_1;
		
		private string _Téléphone;
		
		private string _Taxe_fonc;
		
		private string _Envoi_Courrier;
		
		private string _CD_Fiche;
		
		private string _DM_Fiche;
		
		private string _Code_postale_Immeuble;
		
		private string _Numéro_Immeuble;
		
		private string _Nom_p2;
		
		private string _Reponse;
		
		private string _Modifier_par;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNumeroChanging(int value);
    partial void OnNumeroChanged();
    partial void OnTitreChanging(string value);
    partial void OnTitreChanged();
    partial void OnPrénomChanging(string value);
    partial void OnPrénomChanged();
    partial void OnNom_PropriétaireChanging(string value);
    partial void OnNom_PropriétaireChanged();
    partial void OnNuméro_rue_PropriétaireChanging(string value);
    partial void OnNuméro_rue_PropriétaireChanged();
    partial void OnTypeRuePropriétaireChanging(string value);
    partial void OnTypeRuePropriétaireChanged();
    partial void OnRue_PropriétaireChanging(string value);
    partial void OnRue_PropriétaireChanged();
    partial void OnCode_Postal_PropriétaireChanging(string value);
    partial void OnCode_Postal_PropriétaireChanged();
    partial void OnVille_PropriétaireChanging(string value);
    partial void OnVille_PropriétaireChanged();
    partial void OnTypeRueImmeubleChanging(string value);
    partial void OnTypeRueImmeubleChanged();
    partial void OnCommentaire_2Changing(string value);
    partial void OnCommentaire_2Changed();
    partial void OnRue_ImmeubleChanging(string value);
    partial void OnRue_ImmeubleChanged();
    partial void OnVille_ImmeubleChanging(string value);
    partial void OnVille_ImmeubleChanged();
    partial void OnAsterixChanging(string value);
    partial void OnAsterixChanged();
    partial void OnCommentaire_1Changing(string value);
    partial void OnCommentaire_1Changed();
    partial void OnTéléphoneChanging(string value);
    partial void OnTéléphoneChanged();
    partial void OnTaxe_foncChanging(string value);
    partial void OnTaxe_foncChanged();
    partial void OnEnvoi_CourrierChanging(string value);
    partial void OnEnvoi_CourrierChanged();
    partial void OnCD_FicheChanging(string value);
    partial void OnCD_FicheChanged();
    partial void OnDM_FicheChanging(string value);
    partial void OnDM_FicheChanged();
    partial void OnCode_postale_ImmeubleChanging(string value);
    partial void OnCode_postale_ImmeubleChanged();
    partial void OnNuméro_ImmeubleChanging(string value);
    partial void OnNuméro_ImmeubleChanged();
    partial void OnNom_p2Changing(string value);
    partial void OnNom_p2Changed();
    partial void OnReponseChanging(string value);
    partial void OnReponseChanged();
    partial void OnModifier_parChanging(string value);
    partial void OnModifier_parChanged();
    #endregion
		
		public BaseTMT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Numero
		{
			get
			{
				return this._Numero;
			}
			set
			{
				if ((this._Numero != value))
				{
					this.OnNumeroChanging(value);
					this.SendPropertyChanging();
					this._Numero = value;
					this.SendPropertyChanged("Numero");
					this.OnNumeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titre", DbType="NVarChar(255)")]
		public string Titre
		{
			get
			{
				return this._Titre;
			}
			set
			{
				if ((this._Titre != value))
				{
					this.OnTitreChanging(value);
					this.SendPropertyChanging();
					this._Titre = value;
					this.SendPropertyChanged("Titre");
					this.OnTitreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prénom", DbType="NVarChar(255)")]
		public string Prénom
		{
			get
			{
				return this._Prénom;
			}
			set
			{
				if ((this._Prénom != value))
				{
					this.OnPrénomChanging(value);
					this.SendPropertyChanging();
					this._Prénom = value;
					this.SendPropertyChanged("Prénom");
					this.OnPrénomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nom Propriétaire]", Storage="_Nom_Propriétaire", DbType="NVarChar(255)")]
		public string Nom_Propriétaire
		{
			get
			{
				return this._Nom_Propriétaire;
			}
			set
			{
				if ((this._Nom_Propriétaire != value))
				{
					this.OnNom_PropriétaireChanging(value);
					this.SendPropertyChanging();
					this._Nom_Propriétaire = value;
					this.SendPropertyChanged("Nom_Propriétaire");
					this.OnNom_PropriétaireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Numéro rue Propriétaire]", Storage="_Numéro_rue_Propriétaire", DbType="NVarChar(255)")]
		public string Numéro_rue_Propriétaire
		{
			get
			{
				return this._Numéro_rue_Propriétaire;
			}
			set
			{
				if ((this._Numéro_rue_Propriétaire != value))
				{
					this.OnNuméro_rue_PropriétaireChanging(value);
					this.SendPropertyChanging();
					this._Numéro_rue_Propriétaire = value;
					this.SendPropertyChanged("Numéro_rue_Propriétaire");
					this.OnNuméro_rue_PropriétaireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeRuePropriétaire", DbType="NVarChar(255)")]
		public string TypeRuePropriétaire
		{
			get
			{
				return this._TypeRuePropriétaire;
			}
			set
			{
				if ((this._TypeRuePropriétaire != value))
				{
					this.OnTypeRuePropriétaireChanging(value);
					this.SendPropertyChanging();
					this._TypeRuePropriétaire = value;
					this.SendPropertyChanged("TypeRuePropriétaire");
					this.OnTypeRuePropriétaireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Rue Propriétaire]", Storage="_Rue_Propriétaire", DbType="NVarChar(255)")]
		public string Rue_Propriétaire
		{
			get
			{
				return this._Rue_Propriétaire;
			}
			set
			{
				if ((this._Rue_Propriétaire != value))
				{
					this.OnRue_PropriétaireChanging(value);
					this.SendPropertyChanging();
					this._Rue_Propriétaire = value;
					this.SendPropertyChanged("Rue_Propriétaire");
					this.OnRue_PropriétaireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Code Postal Propriétaire]", Storage="_Code_Postal_Propriétaire", DbType="NVarChar(255)")]
		public string Code_Postal_Propriétaire
		{
			get
			{
				return this._Code_Postal_Propriétaire;
			}
			set
			{
				if ((this._Code_Postal_Propriétaire != value))
				{
					this.OnCode_Postal_PropriétaireChanging(value);
					this.SendPropertyChanging();
					this._Code_Postal_Propriétaire = value;
					this.SendPropertyChanged("Code_Postal_Propriétaire");
					this.OnCode_Postal_PropriétaireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Ville Propriétaire]", Storage="_Ville_Propriétaire", DbType="NVarChar(255)")]
		public string Ville_Propriétaire
		{
			get
			{
				return this._Ville_Propriétaire;
			}
			set
			{
				if ((this._Ville_Propriétaire != value))
				{
					this.OnVille_PropriétaireChanging(value);
					this.SendPropertyChanging();
					this._Ville_Propriétaire = value;
					this.SendPropertyChanged("Ville_Propriétaire");
					this.OnVille_PropriétaireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeRueImmeuble", DbType="NVarChar(255)")]
		public string TypeRueImmeuble
		{
			get
			{
				return this._TypeRueImmeuble;
			}
			set
			{
				if ((this._TypeRueImmeuble != value))
				{
					this.OnTypeRueImmeubleChanging(value);
					this.SendPropertyChanging();
					this._TypeRueImmeuble = value;
					this.SendPropertyChanged("TypeRueImmeuble");
					this.OnTypeRueImmeubleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Commentaire 2]", Storage="_Commentaire_2", DbType="NVarChar(255)")]
		public string Commentaire_2
		{
			get
			{
				return this._Commentaire_2;
			}
			set
			{
				if ((this._Commentaire_2 != value))
				{
					this.OnCommentaire_2Changing(value);
					this.SendPropertyChanging();
					this._Commentaire_2 = value;
					this.SendPropertyChanged("Commentaire_2");
					this.OnCommentaire_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Rue Immeuble]", Storage="_Rue_Immeuble", DbType="NVarChar(255)")]
		public string Rue_Immeuble
		{
			get
			{
				return this._Rue_Immeuble;
			}
			set
			{
				if ((this._Rue_Immeuble != value))
				{
					this.OnRue_ImmeubleChanging(value);
					this.SendPropertyChanging();
					this._Rue_Immeuble = value;
					this.SendPropertyChanged("Rue_Immeuble");
					this.OnRue_ImmeubleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Ville Immeuble]", Storage="_Ville_Immeuble", DbType="NVarChar(255)")]
		public string Ville_Immeuble
		{
			get
			{
				return this._Ville_Immeuble;
			}
			set
			{
				if ((this._Ville_Immeuble != value))
				{
					this.OnVille_ImmeubleChanging(value);
					this.SendPropertyChanging();
					this._Ville_Immeuble = value;
					this.SendPropertyChanged("Ville_Immeuble");
					this.OnVille_ImmeubleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asterix", DbType="NVarChar(255)")]
		public string Asterix
		{
			get
			{
				return this._Asterix;
			}
			set
			{
				if ((this._Asterix != value))
				{
					this.OnAsterixChanging(value);
					this.SendPropertyChanging();
					this._Asterix = value;
					this.SendPropertyChanged("Asterix");
					this.OnAsterixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Commentaire 1]", Storage="_Commentaire_1", DbType="NVarChar(255)")]
		public string Commentaire_1
		{
			get
			{
				return this._Commentaire_1;
			}
			set
			{
				if ((this._Commentaire_1 != value))
				{
					this.OnCommentaire_1Changing(value);
					this.SendPropertyChanging();
					this._Commentaire_1 = value;
					this.SendPropertyChanged("Commentaire_1");
					this.OnCommentaire_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Téléphone", DbType="NVarChar(255)")]
		public string Téléphone
		{
			get
			{
				return this._Téléphone;
			}
			set
			{
				if ((this._Téléphone != value))
				{
					this.OnTéléphoneChanging(value);
					this.SendPropertyChanging();
					this._Téléphone = value;
					this.SendPropertyChanged("Téléphone");
					this.OnTéléphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Taxe fonc]", Storage="_Taxe_fonc", DbType="NVarChar(255)")]
		public string Taxe_fonc
		{
			get
			{
				return this._Taxe_fonc;
			}
			set
			{
				if ((this._Taxe_fonc != value))
				{
					this.OnTaxe_foncChanging(value);
					this.SendPropertyChanging();
					this._Taxe_fonc = value;
					this.SendPropertyChanged("Taxe_fonc");
					this.OnTaxe_foncChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Envoi Courrier]", Storage="_Envoi_Courrier", DbType="NVarChar(255)")]
		public string Envoi_Courrier
		{
			get
			{
				return this._Envoi_Courrier;
			}
			set
			{
				if ((this._Envoi_Courrier != value))
				{
					this.OnEnvoi_CourrierChanging(value);
					this.SendPropertyChanging();
					this._Envoi_Courrier = value;
					this.SendPropertyChanged("Envoi_Courrier");
					this.OnEnvoi_CourrierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CD_Fiche", DbType="NVarChar(255)")]
		public string CD_Fiche
		{
			get
			{
				return this._CD_Fiche;
			}
			set
			{
				if ((this._CD_Fiche != value))
				{
					this.OnCD_FicheChanging(value);
					this.SendPropertyChanging();
					this._CD_Fiche = value;
					this.SendPropertyChanged("CD_Fiche");
					this.OnCD_FicheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM_Fiche", DbType="NVarChar(255)")]
		public string DM_Fiche
		{
			get
			{
				return this._DM_Fiche;
			}
			set
			{
				if ((this._DM_Fiche != value))
				{
					this.OnDM_FicheChanging(value);
					this.SendPropertyChanging();
					this._DM_Fiche = value;
					this.SendPropertyChanged("DM_Fiche");
					this.OnDM_FicheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Code postale Immeuble]", Storage="_Code_postale_Immeuble", DbType="NVarChar(255)")]
		public string Code_postale_Immeuble
		{
			get
			{
				return this._Code_postale_Immeuble;
			}
			set
			{
				if ((this._Code_postale_Immeuble != value))
				{
					this.OnCode_postale_ImmeubleChanging(value);
					this.SendPropertyChanging();
					this._Code_postale_Immeuble = value;
					this.SendPropertyChanged("Code_postale_Immeuble");
					this.OnCode_postale_ImmeubleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Numéro Immeuble]", Storage="_Numéro_Immeuble", DbType="NVarChar(255)")]
		public string Numéro_Immeuble
		{
			get
			{
				return this._Numéro_Immeuble;
			}
			set
			{
				if ((this._Numéro_Immeuble != value))
				{
					this.OnNuméro_ImmeubleChanging(value);
					this.SendPropertyChanging();
					this._Numéro_Immeuble = value;
					this.SendPropertyChanged("Numéro_Immeuble");
					this.OnNuméro_ImmeubleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nom p2]", Storage="_Nom_p2", DbType="NVarChar(255)")]
		public string Nom_p2
		{
			get
			{
				return this._Nom_p2;
			}
			set
			{
				if ((this._Nom_p2 != value))
				{
					this.OnNom_p2Changing(value);
					this.SendPropertyChanging();
					this._Nom_p2 = value;
					this.SendPropertyChanged("Nom_p2");
					this.OnNom_p2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reponse", DbType="NVarChar(255)")]
		public string Reponse
		{
			get
			{
				return this._Reponse;
			}
			set
			{
				if ((this._Reponse != value))
				{
					this.OnReponseChanging(value);
					this.SendPropertyChanging();
					this._Reponse = value;
					this.SendPropertyChanged("Reponse");
					this.OnReponseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Modifier par]", Storage="_Modifier_par", DbType="NVarChar(255)")]
		public string Modifier_par
		{
			get
			{
				return this._Modifier_par;
			}
			set
			{
				if ((this._Modifier_par != value))
				{
					this.OnModifier_parChanging(value);
					this.SendPropertyChanging();
					this._Modifier_par = value;
					this.SendPropertyChanged("Modifier_par");
					this.OnModifier_parChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Fiches")]
	public partial class tbl_Fiches : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Fiche;
		
		private System.Nullable<int> _ID_Pro;
		
		private System.Nullable<int> _ID_Imm;
		
		private string _Asterix;
		
		private string _Commentaire1;
		
		private string _Commentaire2;
		
		private string _EnvoiCourrier;
		
		private string _CD_Fiche;
		
		private string _DM_Fiche;
		
		private string _Reponse;
		
		private string _ModifierPar;
		
		private System.Data.Linq.Binary _SSMA_TimeStamp;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_FicheChanging(int value);
    partial void OnID_FicheChanged();
    partial void OnID_ProChanging(System.Nullable<int> value);
    partial void OnID_ProChanged();
    partial void OnID_ImmChanging(System.Nullable<int> value);
    partial void OnID_ImmChanged();
    partial void OnAsterixChanging(string value);
    partial void OnAsterixChanged();
    partial void OnCommentaire1Changing(string value);
    partial void OnCommentaire1Changed();
    partial void OnCommentaire2Changing(string value);
    partial void OnCommentaire2Changed();
    partial void OnEnvoiCourrierChanging(string value);
    partial void OnEnvoiCourrierChanged();
    partial void OnCD_FicheChanging(string value);
    partial void OnCD_FicheChanged();
    partial void OnDM_FicheChanging(string value);
    partial void OnDM_FicheChanged();
    partial void OnReponseChanging(string value);
    partial void OnReponseChanged();
    partial void OnModifierParChanging(string value);
    partial void OnModifierParChanged();
    partial void OnSSMA_TimeStampChanging(System.Data.Linq.Binary value);
    partial void OnSSMA_TimeStampChanged();
    #endregion
		
		public tbl_Fiches()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Fiche", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int ID_Fiche
		{
			get
			{
				return this._ID_Fiche;
			}
			set
			{
				if ((this._ID_Fiche != value))
				{
					this.OnID_FicheChanging(value);
					this.SendPropertyChanging();
					this._ID_Fiche = value;
					this.SendPropertyChanged("ID_Fiche");
					this.OnID_FicheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Pro", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> ID_Pro
		{
			get
			{
				return this._ID_Pro;
			}
			set
			{
				if ((this._ID_Pro != value))
				{
					this.OnID_ProChanging(value);
					this.SendPropertyChanging();
					this._ID_Pro = value;
					this.SendPropertyChanged("ID_Pro");
					this.OnID_ProChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Imm", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> ID_Imm
		{
			get
			{
				return this._ID_Imm;
			}
			set
			{
				if ((this._ID_Imm != value))
				{
					this.OnID_ImmChanging(value);
					this.SendPropertyChanging();
					this._ID_Imm = value;
					this.SendPropertyChanged("ID_Imm");
					this.OnID_ImmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asterix", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string Asterix
		{
			get
			{
				return this._Asterix;
			}
			set
			{
				if ((this._Asterix != value))
				{
					this.OnAsterixChanging(value);
					this.SendPropertyChanging();
					this._Asterix = value;
					this.SendPropertyChanged("Asterix");
					this.OnAsterixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Commentaire1", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string Commentaire1
		{
			get
			{
				return this._Commentaire1;
			}
			set
			{
				if ((this._Commentaire1 != value))
				{
					this.OnCommentaire1Changing(value);
					this.SendPropertyChanging();
					this._Commentaire1 = value;
					this.SendPropertyChanged("Commentaire1");
					this.OnCommentaire1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Commentaire2", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string Commentaire2
		{
			get
			{
				return this._Commentaire2;
			}
			set
			{
				if ((this._Commentaire2 != value))
				{
					this.OnCommentaire2Changing(value);
					this.SendPropertyChanging();
					this._Commentaire2 = value;
					this.SendPropertyChanged("Commentaire2");
					this.OnCommentaire2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnvoiCourrier", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string EnvoiCourrier
		{
			get
			{
				return this._EnvoiCourrier;
			}
			set
			{
				if ((this._EnvoiCourrier != value))
				{
					this.OnEnvoiCourrierChanging(value);
					this.SendPropertyChanging();
					this._EnvoiCourrier = value;
					this.SendPropertyChanged("EnvoiCourrier");
					this.OnEnvoiCourrierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CD_Fiche", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string CD_Fiche
		{
			get
			{
				return this._CD_Fiche;
			}
			set
			{
				if ((this._CD_Fiche != value))
				{
					this.OnCD_FicheChanging(value);
					this.SendPropertyChanging();
					this._CD_Fiche = value;
					this.SendPropertyChanged("CD_Fiche");
					this.OnCD_FicheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM_Fiche", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string DM_Fiche
		{
			get
			{
				return this._DM_Fiche;
			}
			set
			{
				if ((this._DM_Fiche != value))
				{
					this.OnDM_FicheChanging(value);
					this.SendPropertyChanging();
					this._DM_Fiche = value;
					this.SendPropertyChanged("DM_Fiche");
					this.OnDM_FicheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reponse", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string Reponse
		{
			get
			{
				return this._Reponse;
			}
			set
			{
				if ((this._Reponse != value))
				{
					this.OnReponseChanging(value);
					this.SendPropertyChanging();
					this._Reponse = value;
					this.SendPropertyChanged("Reponse");
					this.OnReponseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifierPar", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string ModifierPar
		{
			get
			{
				return this._ModifierPar;
			}
			set
			{
				if ((this._ModifierPar != value))
				{
					this.OnModifierParChanging(value);
					this.SendPropertyChanging();
					this._ModifierPar = value;
					this.SendPropertyChanged("ModifierPar");
					this.OnModifierParChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSMA_TimeStamp", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary SSMA_TimeStamp
		{
			get
			{
				return this._SSMA_TimeStamp;
			}
			set
			{
				if ((this._SSMA_TimeStamp != value))
				{
					this.OnSSMA_TimeStampChanging(value);
					this.SendPropertyChanging();
					this._SSMA_TimeStamp = value;
					this.SendPropertyChanged("SSMA_TimeStamp");
					this.OnSSMA_TimeStampChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Immeuble")]
	public partial class tbl_Immeuble : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Imm;
		
		private string _TypeRueImm;
		
		private string _RueImm;
		
		private string _VilleImm;
		
		private string _CodePostaleImm;
		
		private string _NumImm;
		
		private string _Reponse;
		
		private string _ModifierPar;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ImmChanging(int value);
    partial void OnID_ImmChanged();
    partial void OnTypeRueImmChanging(string value);
    partial void OnTypeRueImmChanged();
    partial void OnRueImmChanging(string value);
    partial void OnRueImmChanged();
    partial void OnVilleImmChanging(string value);
    partial void OnVilleImmChanged();
    partial void OnCodePostaleImmChanging(string value);
    partial void OnCodePostaleImmChanged();
    partial void OnNumImmChanging(string value);
    partial void OnNumImmChanged();
    partial void OnReponseChanging(string value);
    partial void OnReponseChanged();
    partial void OnModifierParChanging(string value);
    partial void OnModifierParChanged();
    #endregion
		
		public tbl_Immeuble()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Imm", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Imm
		{
			get
			{
				return this._ID_Imm;
			}
			set
			{
				if ((this._ID_Imm != value))
				{
					this.OnID_ImmChanging(value);
					this.SendPropertyChanging();
					this._ID_Imm = value;
					this.SendPropertyChanged("ID_Imm");
					this.OnID_ImmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeRueImm", DbType="NVarChar(255)")]
		public string TypeRueImm
		{
			get
			{
				return this._TypeRueImm;
			}
			set
			{
				if ((this._TypeRueImm != value))
				{
					this.OnTypeRueImmChanging(value);
					this.SendPropertyChanging();
					this._TypeRueImm = value;
					this.SendPropertyChanged("TypeRueImm");
					this.OnTypeRueImmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RueImm", DbType="NVarChar(255)")]
		public string RueImm
		{
			get
			{
				return this._RueImm;
			}
			set
			{
				if ((this._RueImm != value))
				{
					this.OnRueImmChanging(value);
					this.SendPropertyChanging();
					this._RueImm = value;
					this.SendPropertyChanged("RueImm");
					this.OnRueImmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VilleImm", DbType="NVarChar(255)")]
		public string VilleImm
		{
			get
			{
				return this._VilleImm;
			}
			set
			{
				if ((this._VilleImm != value))
				{
					this.OnVilleImmChanging(value);
					this.SendPropertyChanging();
					this._VilleImm = value;
					this.SendPropertyChanged("VilleImm");
					this.OnVilleImmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodePostaleImm", DbType="NVarChar(255)")]
		public string CodePostaleImm
		{
			get
			{
				return this._CodePostaleImm;
			}
			set
			{
				if ((this._CodePostaleImm != value))
				{
					this.OnCodePostaleImmChanging(value);
					this.SendPropertyChanging();
					this._CodePostaleImm = value;
					this.SendPropertyChanged("CodePostaleImm");
					this.OnCodePostaleImmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumImm", DbType="NVarChar(255)")]
		public string NumImm
		{
			get
			{
				return this._NumImm;
			}
			set
			{
				if ((this._NumImm != value))
				{
					this.OnNumImmChanging(value);
					this.SendPropertyChanging();
					this._NumImm = value;
					this.SendPropertyChanged("NumImm");
					this.OnNumImmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reponse", DbType="NVarChar(255)")]
		public string Reponse
		{
			get
			{
				return this._Reponse;
			}
			set
			{
				if ((this._Reponse != value))
				{
					this.OnReponseChanging(value);
					this.SendPropertyChanging();
					this._Reponse = value;
					this.SendPropertyChanged("Reponse");
					this.OnReponseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifierPar", DbType="NVarChar(255)")]
		public string ModifierPar
		{
			get
			{
				return this._ModifierPar;
			}
			set
			{
				if ((this._ModifierPar != value))
				{
					this.OnModifierParChanging(value);
					this.SendPropertyChanging();
					this._ModifierPar = value;
					this.SendPropertyChanged("ModifierPar");
					this.OnModifierParChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Proprio")]
	public partial class tbl_Proprio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Pro;
		
		private string _Titre;
		
		private string _Prenom;
		
		private string _Nom_Pro;
		
		private string _Nom_p2;
		
		private string _NumRuePro;
		
		private string _TypeRuePro;
		
		private string _RueProp;
		
		private string _CodePostalPro;
		
		private string _VillePro;
		
		private string _Tel;
		
		private string _TaxeFonc;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ProChanging(int value);
    partial void OnID_ProChanged();
    partial void OnTitreChanging(string value);
    partial void OnTitreChanged();
    partial void OnPrenomChanging(string value);
    partial void OnPrenomChanged();
    partial void OnNom_ProChanging(string value);
    partial void OnNom_ProChanged();
    partial void OnNom_p2Changing(string value);
    partial void OnNom_p2Changed();
    partial void OnNumRueProChanging(string value);
    partial void OnNumRueProChanged();
    partial void OnTypeRueProChanging(string value);
    partial void OnTypeRueProChanged();
    partial void OnRuePropChanging(string value);
    partial void OnRuePropChanged();
    partial void OnCodePostalProChanging(string value);
    partial void OnCodePostalProChanged();
    partial void OnVilleProChanging(string value);
    partial void OnVilleProChanged();
    partial void OnTelChanging(string value);
    partial void OnTelChanged();
    partial void OnTaxeFoncChanging(string value);
    partial void OnTaxeFoncChanged();
    #endregion
		
		public tbl_Proprio()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Pro", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Pro
		{
			get
			{
				return this._ID_Pro;
			}
			set
			{
				if ((this._ID_Pro != value))
				{
					this.OnID_ProChanging(value);
					this.SendPropertyChanging();
					this._ID_Pro = value;
					this.SendPropertyChanged("ID_Pro");
					this.OnID_ProChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titre", DbType="NVarChar(255)")]
		public string Titre
		{
			get
			{
				return this._Titre;
			}
			set
			{
				if ((this._Titre != value))
				{
					this.OnTitreChanging(value);
					this.SendPropertyChanging();
					this._Titre = value;
					this.SendPropertyChanged("Titre");
					this.OnTitreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenom", DbType="NVarChar(255)")]
		public string Prenom
		{
			get
			{
				return this._Prenom;
			}
			set
			{
				if ((this._Prenom != value))
				{
					this.OnPrenomChanging(value);
					this.SendPropertyChanging();
					this._Prenom = value;
					this.SendPropertyChanged("Prenom");
					this.OnPrenomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom_Pro", DbType="NVarChar(255)")]
		public string Nom_Pro
		{
			get
			{
				return this._Nom_Pro;
			}
			set
			{
				if ((this._Nom_Pro != value))
				{
					this.OnNom_ProChanging(value);
					this.SendPropertyChanging();
					this._Nom_Pro = value;
					this.SendPropertyChanged("Nom_Pro");
					this.OnNom_ProChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom_p2", DbType="NVarChar(255)")]
		public string Nom_p2
		{
			get
			{
				return this._Nom_p2;
			}
			set
			{
				if ((this._Nom_p2 != value))
				{
					this.OnNom_p2Changing(value);
					this.SendPropertyChanging();
					this._Nom_p2 = value;
					this.SendPropertyChanged("Nom_p2");
					this.OnNom_p2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumRuePro", DbType="NVarChar(255)")]
		public string NumRuePro
		{
			get
			{
				return this._NumRuePro;
			}
			set
			{
				if ((this._NumRuePro != value))
				{
					this.OnNumRueProChanging(value);
					this.SendPropertyChanging();
					this._NumRuePro = value;
					this.SendPropertyChanged("NumRuePro");
					this.OnNumRueProChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeRuePro", DbType="NVarChar(255)")]
		public string TypeRuePro
		{
			get
			{
				return this._TypeRuePro;
			}
			set
			{
				if ((this._TypeRuePro != value))
				{
					this.OnTypeRueProChanging(value);
					this.SendPropertyChanging();
					this._TypeRuePro = value;
					this.SendPropertyChanged("TypeRuePro");
					this.OnTypeRueProChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RueProp", DbType="NVarChar(255)")]
		public string RueProp
		{
			get
			{
				return this._RueProp;
			}
			set
			{
				if ((this._RueProp != value))
				{
					this.OnRuePropChanging(value);
					this.SendPropertyChanging();
					this._RueProp = value;
					this.SendPropertyChanged("RueProp");
					this.OnRuePropChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodePostalPro", DbType="NVarChar(255)")]
		public string CodePostalPro
		{
			get
			{
				return this._CodePostalPro;
			}
			set
			{
				if ((this._CodePostalPro != value))
				{
					this.OnCodePostalProChanging(value);
					this.SendPropertyChanging();
					this._CodePostalPro = value;
					this.SendPropertyChanged("CodePostalPro");
					this.OnCodePostalProChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VillePro", DbType="NVarChar(255)")]
		public string VillePro
		{
			get
			{
				return this._VillePro;
			}
			set
			{
				if ((this._VillePro != value))
				{
					this.OnVilleProChanging(value);
					this.SendPropertyChanging();
					this._VillePro = value;
					this.SendPropertyChanged("VillePro");
					this.OnVilleProChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="NVarChar(255)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this.OnTelChanging(value);
					this.SendPropertyChanging();
					this._Tel = value;
					this.SendPropertyChanged("Tel");
					this.OnTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxeFonc", DbType="NVarChar(255)")]
		public string TaxeFonc
		{
			get
			{
				return this._TaxeFonc;
			}
			set
			{
				if ((this._TaxeFonc != value))
				{
					this.OnTaxeFoncChanging(value);
					this.SendPropertyChanging();
					this._TaxeFonc = value;
					this.SendPropertyChanged("TaxeFonc");
					this.OnTaxeFoncChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
